/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./docs/**/*.{md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: {
          100: "var(--sds-color-black-100)",
          200: "var(--sds-color-black-200)",
          300: "var(--sds-color-black-300)",
          400: "var(--sds-color-black-400)",
          500: "var(--sds-color-black-500)",
          600: "var(--sds-color-black-600)",
          700: "var(--sds-color-black-700)",
          800: "var(--sds-color-black-800)",
          900: "var(--sds-color-black-900)",
          1000: "var(--sds-color-black-1000)",
        },
        brand: {
          100: "var(--sds-color-brand-100)",
          200: "var(--sds-color-brand-200)",
          300: "var(--sds-color-brand-300)",
          400: "var(--sds-color-brand-400)",
          500: "var(--sds-color-brand-500)",
          600: "var(--sds-color-brand-600)",
          700: "var(--sds-color-brand-700)",
          800: "var(--sds-color-brand-800)",
          900: "var(--sds-color-brand-900)",
          1000: "var(--sds-color-brand-1000)",
        },
        gray: {
          100: "var(--sds-color-gray-100)",
          200: "var(--sds-color-gray-200)",
          300: "var(--sds-color-gray-300)",
          400: "var(--sds-color-gray-400)",
          500: "var(--sds-color-gray-500)",
          600: "var(--sds-color-gray-600)",
          700: "var(--sds-color-gray-700)",
          800: "var(--sds-color-gray-800)",
          900: "var(--sds-color-gray-900)",
          1000: "var(--sds-color-gray-1000)",
        },
        green: {
          100: "var(--sds-color-green-100)",
          200: "var(--sds-color-green-200)",
          300: "var(--sds-color-green-300)",
          400: "var(--sds-color-green-400)",
          500: "var(--sds-color-green-500)",
          600: "var(--sds-color-green-600)",
          700: "var(--sds-color-green-700)",
          800: "var(--sds-color-green-800)",
          900: "var(--sds-color-green-900)",
          1000: "var(--sds-color-green-1000)",
        },
        pink: {
          100: "var(--sds-color-pink-100)",
          200: "var(--sds-color-pink-200)",
          300: "var(--sds-color-pink-300)",
          400: "var(--sds-color-pink-400)",
          500: "var(--sds-color-pink-500)",
          600: "var(--sds-color-pink-600)",
          700: "var(--sds-color-pink-700)",
          800: "var(--sds-color-pink-800)",
          900: "var(--sds-color-pink-900)",
          1000: "var(--sds-color-pink-1000)",
        },
        red: {
          100: "var(--sds-color-red-100)",
          200: "var(--sds-color-red-200)",
          300: "var(--sds-color-red-300)",
          400: "var(--sds-color-red-400)",
          500: "var(--sds-color-red-500)",
          600: "var(--sds-color-red-600)",
          700: "var(--sds-color-red-700)",
          800: "var(--sds-color-red-800)",
          900: "var(--sds-color-red-900)",
          1000: "var(--sds-color-red-1000)",
        },
        slate: {
          100: "var(--sds-color-slate-100)",
          200: "var(--sds-color-slate-200)",
          300: "var(--sds-color-slate-300)",
          400: "var(--sds-color-slate-400)",
          500: "var(--sds-color-slate-500)",
          600: "var(--sds-color-slate-600)",
          700: "var(--sds-color-slate-700)",
          800: "var(--sds-color-slate-800)",
          900: "var(--sds-color-slate-900)",
          1000: "var(--sds-color-slate-1000)",
        },
        white: {
          100: "var(--sds-color-white-100)",
          200: "var(--sds-color-white-200)",
          300: "var(--sds-color-white-300)",
          400: "var(--sds-color-white-400)",
          500: "var(--sds-color-white-500)",
          600: "var(--sds-color-white-600)",
          700: "var(--sds-color-white-700)",
          800: "var(--sds-color-white-800)",
          900: "var(--sds-color-white-900)",
          1000: "var(--sds-color-white-1000)",
        },
        yellow: {
          100: "var(--sds-color-yellow-100)",
          200: "var(--sds-color-yellow-200)",
          300: "var(--sds-color-yellow-300)",
          400: "var(--sds-color-yellow-400)",
          500: "var(--sds-color-yellow-500)",
          600: "var(--sds-color-yellow-600)",
          700: "var(--sds-color-yellow-700)",
          800: "var(--sds-color-yellow-800)",
          900: "var(--sds-color-yellow-900)",
          1000: "var(--sds-color-yellow-1000)",
        },
        icon: {
          brand: {
            DEFAULT: "var(--sds-color-icon-brand-default)",
            secondary: "var(--sds-color-icon-brand-secondary)",
            tertiary: "var(--sds-color-icon-brand-tertiary)",
            "on-brand": "var(--sds-color-icon-brand-on-brand)",
            "on-brand-secondary": "var(--sds-color-icon-brand-on-brand-secondary)",
            "on-brand-tertiary": "var(--sds-color-icon-brand-on-brand-tertiary)",
          },
          danger: {
            DEFAULT: "var(--sds-color-icon-danger-default)",
            secondary: "var(--sds-color-icon-danger-secondary)",
            tertiary: "var(--sds-color-icon-danger-tertiary)",
            "on-danger": "var(--sds-color-icon-danger-on-danger)",
            "on-danger-secondary": "var(--sds-color-icon-danger-on-danger-secondary)",
            "on-danger-tertiary": "var(--sds-color-icon-danger-on-danger-tertiary)",
          },
          default: {
            DEFAULT: "var(--sds-color-icon-default-default)",
            secondary: "var(--sds-color-icon-default-secondary)",
            tertiary: "var(--sds-color-icon-default-tertiary)",
          },
          disabled: {
            DEFAULT: "var(--sds-color-icon-disabled-default)",
            "on-disabled": "var(--sds-color-icon-disabled-on-disabled)",
          },
          neutral: {
            DEFAULT: "var(--sds-color-icon-neutral-default)",
            secondary: "var(--sds-color-icon-neutral-secondary)",
            tertiary: "var(--sds-color-icon-neutral-tertiary)",
            "on-neutral": "var(--sds-color-icon-neutral-on-neutral)",
            "on-neutral-secondary": "var(--sds-color-icon-neutral-on-neutral-secondary)",
            "on-neutral-tertiary": "var(--sds-color-icon-neutral-on-neutral-tertiary)",
          },
          positive: {
            DEFAULT: "var(--sds-color-icon-positive-default)",
            secondary: "var(--sds-color-icon-positive-secondary)",
            tertiary: "var(--sds-color-icon-positive-tertiary)",
            "on-positive": "var(--sds-color-icon-positive-on-positive)",
            "on-positive-secondary": "var(--sds-color-icon-positive-on-positive-secondary)",
            "on-positive-tertiary": "var(--sds-color-icon-positive-on-positive-tertiary)",
          },
          utilities: {
            icon: "var(--sds-color-icon-utilities-icon)",
            "icon-on-measurement":
              "var(--sds-color-icon-utilities-icon-on-measurement)",
          },
          warning: {
            DEFAULT: "var(--sds-color-icon-warning-default)",
            secondary: "var(--sds-color-icon-warning-secondary)",
            tertiary: "var(--sds-color-icon-warning-tertiary)",
            "on-warning": "var(--sds-color-icon-warning-on-warning)",
            "on-warning-secondary": "var(--sds-color-icon-warning-on-warning-secondary)",
            "on-warning-tertiary": "var(--sds-color-icon-warning-on-warning-tertiary)",
          },
        },
      },
      backgroundColor: {
        brand: {
          DEFAULT: "var(--sds-color-background-brand-default)",
          hover: "var(--sds-color-background-brand-hover)",
          secondary: "var(--sds-color-background-brand-secondary)",
          "secondary-hover": "var(--sds-color-background-brand-secondary-hover)",
          tertiary: "var(--sds-color-background-brand-tertiary)",
          "tertiary-hover": "var(--sds-color-background-brand-tertiary-hover)",
        },
        danger: {
          DEFAULT: "var(--sds-color-background-danger-default)",
          hover: "var(--sds-color-background-danger-hover)",
          secondary: "var(--sds-color-background-danger-secondary)",
          "secondary-hover": "var(--sds-color-background-danger-secondary-hover)",
          tertiary: "var(--sds-color-background-danger-tertiary)",
          "tertiary-hover": "var(--sds-color-background-danger-tertiary-hover)",
        },
        default: {
          DEFAULT: "var(--sds-color-background-default-default)",
          hover: "var(--sds-color-background-default-default-hover)",
          secondary: "var(--sds-color-background-default-secondary)",
          "secondary-hover": "var(--sds-color-background-default-secondary-hover)",
          tertiary: "var(--sds-color-background-default-tertiary)",
          "tertiary-hover": "var(--sds-color-background-default-tertiary-hover)",
        },
        disabled: {
          DEFAULT: "var(--sds-color-background-disabled-default)",
        },
        neutral: {
          DEFAULT: "var(--sds-color-background-neutral-default)",
          hover: "var(--sds-color-background-neutral-hover)",
          secondary: "var(--sds-color-background-neutral-secondary)",
          "secondary-hover": "var(--sds-color-background-neutral-secondary-hover)",
          tertiary: "var(--sds-color-background-neutral-tertiary)",
          "tertiary-hover": "var(--sds-color-background-neutral-tertiary-hover)",
        },
        positive: {
          DEFAULT: "var(--sds-color-background-positive-default)",
          hover: "var(--sds-color-background-positive-hover)",
          secondary: "var(--sds-color-background-positive-secondary)",
          "secondary-hover": "var(--sds-color-background-positive-secondary-hover)",
          tertiary: "var(--sds-color-background-positive-tertiary)",
          "tertiary-hover": "var(--sds-color-background-positive-tertiary-hover)",
        },
        utilities: {
          blanket: "var(--sds-color-background-utilities-blanket)",
          measurement: "var(--sds-color-background-utilities-measurement)",
          overlay: "var(--sds-color-background-utilities-overlay)",
          scrim: "var(--sds-color-background-utilities-scrim)",
        },
        warning: {
          DEFAULT: "var(--sds-color-background-warning-default)",
          hover: "var(--sds-color-background-warning-hover)",
          secondary: "var(--sds-color-background-warning-secondary)",
          "secondary-hover": "var(--sds-color-background-warning-secondary-hover)",
          tertiary: "var(--sds-color-background-warning-tertiary)",
          "tertiary-hover": "var(--sds-color-background-warning-tertiary-hover)",
        },
      },
      borderColor: {
        brand: {
          DEFAULT: "var(--sds-color-border-brand-default)",
          secondary: "var(--sds-color-border-brand-secondary)",
          tertiary: "var(--sds-color-border-brand-tertiary)",
        },
        danger: {
          DEFAULT: "var(--sds-color-border-danger-default)",
          secondary: "var(--sds-color-border-danger-secondary)",
          tertiary: "var(--sds-color-border-danger-tertiary)",
        },
        default: {
          DEFAULT: "var(--sds-color-border-default-default)",
          secondary: "var(--sds-color-border-default-secondary)",
          tertiary: "var(--sds-color-border-default-tertiary)",
        },
        disabled: {
          DEFAULT: "var(--sds-color-border-disabled-default)",
        },
        neutral: {
          DEFAULT: "var(--sds-color-border-neutral-default)",
          secondary: "var(--sds-color-border-neutral-secondary)",
          tertiary: "var(--sds-color-border-neutral-tertiary)",
        },
        positive: {
          DEFAULT: "var(--sds-color-border-positive-default)",
          secondary: "var(--sds-color-border-positive-secondary)",
          tertiary: "var(--sds-color-border-positive-tertiary)",
        },
        utilities: {
          measurement: "var(--sds-color-border-utilities-measurement)",
          swatch: "var(--sds-color-border-utilities-swatch)",
        },
        warning: {
          DEFAULT: "var(--sds-color-border-warning-default)",
          secondary: "var(--sds-color-border-warning-secondary)",
          tertiary: "var(--sds-color-border-warning-tertiary)",
        },
      },
      textColor: {
        brand: {
          DEFAULT: "var(--sds-color-text-brand-default)",
          secondary: "var(--sds-color-text-brand-secondary)",
          tertiary: "var(--sds-color-text-brand-tertiary)",
          "on-brand": "var(--sds-color-text-brand-on-brand)",
          "on-brand-secondary": "var(--sds-color-text-brand-on-brand-secondary)",
          "on-brand-tertiary": "var(--sds-color-text-brand-on-brand-tertiary)",
        },
        danger: {
          DEFAULT: "var(--sds-color-text-danger-default)",
          secondary: "var(--sds-color-text-danger-secondary)",
          tertiary: "var(--sds-color-text-danger-tertiary)",
          "on-danger": "var(--sds-color-text-danger-on-danger)",
          "on-danger-secondary": "var(--sds-color-text-danger-on-danger-secondary)",
          "on-danger-tertiary": "var(--sds-color-text-danger-on-danger-tertiary)",
        },
        default: {
          DEFAULT: "var(--sds-color-text-default-default)",
          secondary: "var(--sds-color-text-default-secondary)",
          tertiary: "var(--sds-color-text-default-tertiary)",
        },
        disabled: {
          DEFAULT: "var(--sds-color-text-disabled-default)",
          "on-disabled": "var(--sds-color-text-disabled-on-disabled)",
        },
        neutral: {
          DEFAULT: "var(--sds-color-text-neutral-default)",
          secondary: "var(--sds-color-text-neutral-secondary)",
          tertiary: "var(--sds-color-text-neutral-tertiary)",
          "on-neutral": "var(--sds-color-text-neutral-on-neutral)",
          "on-neutral-secondary": "var(--sds-color-text-neutral-on-neutral-secondary)",
          "on-neutral-tertiary": "var(--sds-color-text-neutral-on-neutral-tertiary)",
        },
        positive: {
          DEFAULT: "var(--sds-color-text-positive-default)",
          secondary: "var(--sds-color-text-positive-secondary)",
          tertiary: "var(--sds-color-text-positive-tertiary)",
          "on-positive": "var(--sds-color-text-positive-on-positive)",
          "on-positive-secondary": "var(--sds-color-text-positive-on-positive-secondary)",
          "on-positive-tertiary": "var(--sds-color-text-positive-on-positive-tertiary)",
        },
        utilities: {
          "text-on-measurement": "var(--sds-color-text-utilities-text-on-measurement)",
          "text-on-overlay": "var(--sds-color-text-utilities-text-on-overlay)",
        },
        warning: {
          DEFAULT: "var(--sds-color-text-warning-default)",
          secondary: "var(--sds-color-text-warning-secondary)",
          tertiary: "var(--sds-color-text-warning-tertiary)",
          "on-warning": "var(--sds-color-text-warning-on-warning)",
          "on-warning-secondary": "var(--sds-color-text-warning-on-warning-secondary)",
          "on-warning-tertiary": "var(--sds-color-text-warning-on-warning-tertiary)",
        },
      },
      spacing: {
        0: "var(--sds-size-space-0)",
        "0.5": "var(--sds-size-space-050)",
        1: "var(--sds-size-space-100)",
        "1.5": "var(--sds-size-space-150)",
        2: "var(--sds-size-space-200)",
        3: "var(--sds-size-space-300)",
        4: "var(--sds-size-space-400)",
        6: "var(--sds-size-space-600)",
        8: "var(--sds-size-space-800)",
        12: "var(--sds-size-space-1200)",
        16: "var(--sds-size-space-1600)",
        24: "var(--sds-size-space-2400)",
        40: "var(--sds-size-space-4000)",
        "neg-1": "var(--sds-size-space-negative-100)",
        "neg-2": "var(--sds-size-space-negative-200)",
        "neg-3": "var(--sds-size-space-negative-300)",
        "neg-4": "var(--sds-size-space-negative-400)",
        "neg-6": "var(--sds-size-space-negative-600)",
        "icon-sm": "var(--sds-size-icon-small)",
        "icon-md": "var(--sds-size-icon-medium)",
        "icon-lg": "var(--sds-size-icon-large)",
      },
      fontSize: {
        "scale-01": "var(--sds-typography-scale-01)",
        "scale-02": "var(--sds-typography-scale-02)",
        "scale-03": "var(--sds-typography-scale-03)",
        "scale-04": "var(--sds-typography-scale-04)",
        "scale-05": "var(--sds-typography-scale-05)",
        "scale-06": "var(--sds-typography-scale-06)",
        "scale-07": "var(--sds-typography-scale-07)",
        "scale-08": "var(--sds-typography-scale-08)",
        "scale-09": "var(--sds-typography-scale-09)",
        "scale-10": "var(--sds-typography-scale-10)",
        "body-sm": "var(--sds-typography-body-size-small)",
        "body-md": "var(--sds-typography-body-size-medium)",
        "body-lg": "var(--sds-typography-body-size-large)",
        "code-sm": "var(--sds-typography-code-size-small)",
        "code-md": "var(--sds-typography-code-size-base)",
        "code-lg": "var(--sds-typography-code-size-large)",
        "heading-sm": "var(--sds-typography-heading-size-small)",
        "heading-md": "var(--sds-typography-heading-size-base)",
        "heading-lg": "var(--sds-typography-heading-size-large)",
        "subheading-sm": "var(--sds-typography-subheading-size-small)",
        "subheading-md": "var(--sds-typography-subheading-size-medium)",
        "subheading-lg": "var(--sds-typography-subheading-size-large)",
        "subtitle-sm": "var(--sds-typography-subtitle-size-small)",
        "subtitle-md": "var(--sds-typography-subtitle-size-base)",
        "subtitle-lg": "var(--sds-typography-subtitle-size-large)",
        "title-page-sm": "var(--sds-typography-title-page-size-small)",
        "title-page-md": "var(--sds-typography-title-page-size-base)",
        "title-page-lg": "var(--sds-typography-title-page-size-large)",
        "title-hero": "var(--sds-typography-title-hero-size)",
      },
      fontFamily: {
        sans: "var(--sds-typography-body-font-family)",
        "sans-primitive": "var(--sds-typography-family-sans)",
        heading: "var(--sds-typography-heading-font-family)",
        subheading: "var(--sds-typography-subheading-font-family)",
        subtitle: "var(--sds-typography-subtitle-font-family)",
        "title-hero": "var(--sds-typography-title-hero-font-family)",
        "title-page": "var(--sds-typography-title-page-font-family)",
        serif: "var(--sds-typography-family-serif)",
        mono: "var(--sds-typography-code-font-family)",
        "mono-primitive": "var(--sds-typography-family-mono)",
      },
      fontWeight: {
        thin: "var(--sds-typography-weight-thin)",
        extralight: "var(--sds-typography-weight-extra-light)",
        light: "var(--sds-typography-weight-light)",
        normal: "var(--sds-typography-weight-regular)",
        medium: "var(--sds-typography-weight-medium)",
        semibold: "var(--sds-typography-weight-semibold)",
        bold: "var(--sds-typography-weight-bold)",
        extrabold: "var(--sds-typography-weight-extra-bold)",
        black: "var(--sds-typography-weight-black)",
        "body-regular": "var(--sds-typography-body-font-weight-regular)",
        "body-strong": "var(--sds-typography-body-font-weight-strong)",
        "code": "var(--sds-typography-code-font-weight)",
        heading: "var(--sds-typography-heading-font-weight)",
        subheading: "var(--sds-typography-subheading-font-weight)",
        subtitle: "var(--sds-typography-subtitle-font-weight)",
        "title-hero": "var(--sds-typography-title-hero-font-weight)",
        "title-page": "var(--sds-typography-title-page-font-weight)",
      },
      borderRadius: {
        sm: "var(--sds-size-radius-100)",
        md: "var(--sds-size-radius-200)",
        lg: "var(--sds-size-radius-400)",
        full: "var(--sds-size-radius-full)",
      },
      borderWidth: {
        DEFAULT: "var(--sds-size-stroke-border)",
        2: "var(--sds-size-stroke-focus-ring)",
      },
      blur: {
        100: "var(--sds-size-blur-100)",
      },
      sds: {
        responsive: {
          device: "var(--sds-responsive-device)",
          "device-width": "var(--sds-responsive-device-width)",
          "root-font-size": "var(--sds-responsive-root-font-size)",
          scale: "var(--sds-responsive-scale)",
        },
        depth: {
          0: "var(--sds-size-depth-0)",
          25: "var(--sds-size-depth-025)",
          100: "var(--sds-size-depth-100)",
          200: "var(--sds-size-depth-200)",
          400: "var(--sds-size-depth-400)",
          800: "var(--sds-size-depth-800)",
          1200: "var(--sds-size-depth-1200)",
          "neg-25": "var(--sds-size-depth-negative-025)",
          "neg-100": "var(--sds-size-depth-negative-100)",
          "neg-200": "var(--sds-size-depth-negative-200)",
          "neg-400": "var(--sds-size-depth-negative-400)",
          "neg-800": "var(--sds-size-depth-negative-800)",
          "neg-1200": "var(--sds-size-depth-negative-1200)",
        },
        typography: {
          "body-font-style-italic": "var(--sds-typography-body-font-style-italic)",
          "weight-thin-italic": "var(--sds-typography-weight-thin-italic)",
          "weight-extralight-italic":
            "var(--sds-typography-weight-extralight-italic)",
          "weight-light-italic": "var(--sds-typography-weight-light-italic)",
          "weight-regular-italic": "var(--sds-typography-weight-regular-italic)",
          "weight-medium-italic": "var(--sds-typography-weight-medium-italic)",
          "weight-semibold-italic": "var(--sds-typography-weight-semibold-italic)",
          "weight-bold-italic": "var(--sds-typography-weight-bold-italic)",
          "weight-extra-bold-italic":
            "var(--sds-typography-weight-extra-bold-italic)",
          "weight-black-italic": "var(--sds-typography-weight-black-italic)",
        },
      },
    },
  },
};
